version: "3.2"

services:
#Mysql Container
  db:
    image: mysql/mysql-server:5.7
    restart: always
    volumes:
      - glpi-db:/var/lib/mysql
    env_file:
      - ./mysql.env

#GLPI Container
  app:
    #image: pvrmza/docker-glpi
    image: docker-glpi:latest
    restart: always
    hostname: glpi
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - glpi-plugins:/var/www/html/glpi/plugins
      - glpi-files:/var/www/html/glpi/files
    environment:
      - TIMEZONE=America/Argentina/Mendoza
      - GLPI_DATABASE_HOST=db
      - GLPI_DATABASE_USER=glpi
      - GLPI_DATABASE_PASS=Cambiame
      - GLPI_DATABASE_NAME=glpidb
      - GLPI_INSTALLED=true

volumes:
        glpi-db:
        glpi-plugins:
        glpi-files:
