version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    restart: always

#GLPI Container
  glpi:
    image: pvrmza/docker-glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/glpi/plugins:/var/www/html/glpi/plugins
      - /opt/glpi/files:/var/www/html/glpi/files
    environment:
      - TIMEZONE=America/Argentina/Mendoza
    restart: always